In [ ]:
!pip install pandas

### Import Required Libraries

In [1]:
import pandas as pd
import os

## Set Data Folder Path

In [2]:
raw_folder_path = "data/raw"
processed_folder_path = "data/processed"

In [ ]:


for file in os.listdir(raw_folder_path):
    if file.endswith(".csv"):
        file_path = os.path.join(raw_folder_path, file)

        # read csv
        df = pd.read_csv(file_path, encoding="utf-8-sig")
        print(f"Read file: {file}")

Column Name
zilla_name,seat_id ,seat_name,center_no,center_name,legal_vote,cancel_vote,Absent_vote,total_vote,candidate_name,symbol,candidate_vote

### Combine Multiple Raw CSV Files into One Dataset

This section reads all CSV files from the **raw folder**, processes them, and saves a combined dataset into the **processed folder**.

---

In [49]:
combined_all_data = []

for file in os.listdir(raw_folder_path):
    if file.endswith(".csv"):
        file_path = os.path.join(raw_folder_path, file)

        # Read CSV
        df = pd.read_csv(file_path, encoding="utf-8-sig")

        # Select specific columns
        df_selected = df[["zilla_name", "seat_id","seat_name","center_no","center_name","legal_vote","cancel_vote","Absent_vote","total_vote","candidate_name","symbol","candidate_vote"]]   # change to your column names

        combined_all_data.append(df_selected)

# Combine all data
combined_all_df= pd.concat(combined_all_data, ignore_index=True)

 
output_file = os.path.join(processed_folder_path, "all_combined.csv")
# Save to new CSV
combined_all_df.to_csv(output_file, index=False, encoding="utf-8-sig")

print("File created:{output_file}")

File created:{output_file}

### Load Combined Dataset and Perform Basic Data Check

This section loads the previously saved combined dataset and performs initial data quality checks.

---

In [50]:
file_to_read = os.path.join(processed_folder_path, "all_combined.csv")
df = pd.read_csv(file_to_read, encoding="utf-8-sig")

df.info()
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289908 entries, 0 to 289907
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   zilla_name      289908 non-null  object
 1   seat_id         289908 non-null  int64
 2   seat_name       289908 non-null  object
 3   center_no       289908 non-null  object
 4   center_name     289908 non-null  object
 5   legal_vote      289908 non-null  object
 6   cancel_vote     289908 non-null  object
 7   Absent_vote     289908 non-null  object
 8   total_vote      289908 non-null  object
 9   candidate_name  289908 non-null  object
 10  symbol          289908 non-null  object
 11  candidate_vote  289908 non-null  object
dtypes: int64(1), object(11)
memory usage: 26.5+ MB
zilla_name        0
seat_id           0
seat_name         0
center_no         0
center_name       0
legal_vote        0
cancel_vote       0
Absent_vote       0
total_vote        0
candidate_name    0
symbol            0
candidate_vote    0
dtype: int64

### Convert Columns to Proper Data Types

This section ensures that numerical columns are correctly stored as integers.

---

In [ ]:
df["center_no"] = df["center_no"].astype(int)
df["legal_vote"] = df["legal_vote"].astype(int)
df["Absent_vote"] = df["Absent_vote"].astype(int)
df["total_vote"] = df["total_vote"].astype(int)
df["candidate_vote"] = df["candidate_vote"].astype(int)
df["cancel_vote"] = df["cancel_vote"].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289908 entries, 0 to 289907
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   zilla_name      289908 non-null  object
 1   seat_id         289908 non-null  int64
 2   seat_name       289908 non-null  object
 3   center_no       289908 non-null  int64
 4   center_name     289908 non-null  object
 5   legal_vote      289908 non-null  int64
 6   cancel_vote     289908 non-null  int64
 7   Absent_vote     289908 non-null  int64
 8   total_vote      289908 non-null  int64
 9   candidate_name  289908 non-null  object
 10  symbol          289908 non-null  object
 11  candidate_vote  289908 non-null  int64
dtypes: int64(7), object(5)
memory usage: 26.5+ MB

### Extract Unique Seat Information and Save as Separate File

This section creates a **seat-level dataset** from the combined election data.

---

In [51]:

file_to_read = os.path.join(processed_folder_path, "all_combined.csv")
combined_df = pd.read_csv(file_to_read, encoding="utf-8-sig")
selected_seat_df = combined_df[["zilla_name", "seat_id","seat_name"]].drop_duplicates()
selected_seat_df["seat_id"] = selected_seat_df["seat_id"].astype(int)
# Reset index
df_selected_seat = selected_seat_df.reset_index(drop=True)
display(df_selected_seat)
output_file_seat = os.path.join(processed_folder_path, "seats.csv")
# Save to new CSV
selected_seat_df.to_csv(output_file_seat, index=False, encoding="utf-8-sig")
print("File created:")

    zilla_name  seat_id    seat_name
0    কক্সবাজার        1  কক্সবাজার-১
1    কক্সবাজার        2  কক্সবাজার-২
2    কক্সবাজার        3  কক্সবাজার-৩
3    কক্সবাজার        4  কক্সবাজার-৪
4    কিশোরগঞ্জ        5  কিশোরগঞ্জ-১
..         ...      ...          ...
292  সুনামগঞ্জ      293  সুনামগঞ্জ-৫
293    হবিগঞ্জ      294    হবিগঞ্জ-১
294    হবিগঞ্জ      295    হবিগঞ্জ-২
295    হবিগঞ্জ      296    হবিগঞ্জ-৩
296    হবিগঞ্জ      297    হবিগঞ্জ-৪

[297 rows x 3 columns]

File created:

### Extract Polling Center-Level Data and Save as Separate File

This section creates a **polling center summary dataset** from the combined election data.

---

In [69]:
file_to_read = os.path.join(processed_folder_path, "all_combined.csv")
combined_df = pd.read_csv(file_to_read, encoding="utf-8-sig")
selected_Pooling_center_df = combined_df[[ "seat_id","center_no","center_name","legal_vote","cancel_vote","Absent_vote","total_vote"]].drop_duplicates()
# Reset index
selected_Pooling_center_df = selected_Pooling_center_df.reset_index(drop=True)



selected_Pooling_center_df["seat_id"] = selected_Pooling_center_df["seat_id"].astype(int)
selected_Pooling_center_df["center_no"] = selected_Pooling_center_df["center_no"].astype(int)
selected_Pooling_center_df["legal_vote"] = selected_Pooling_center_df["legal_vote"].astype(int)
selected_Pooling_center_df["cancel_vote"] = selected_Pooling_center_df["cancel_vote"].astype(int)


selected_Pooling_center_df["Absent_vote"] = selected_Pooling_center_df["Absent_vote"].astype(int)
selected_Pooling_center_df["total_vote"] = selected_Pooling_center_df["total_vote"].astype(int)


selected_Pooling_center_df["cast_vote"] = selected_Pooling_center_df["legal_vote"] + selected_Pooling_center_df["cancel_vote"]
selected_Pooling_center_df["cast_vote"] = selected_Pooling_center_df["cast_vote"].astype(int)

display(selected_Pooling_center_df)
output_file = os.path.join(processed_folder_path, "pooling_centres.csv")
# Save to new CSV
selected_Pooling_center_df.to_csv(output_file, index=False, encoding="utf-8-sig")
print("File created:")

,seat_id,center_no,center_name,legal_vote,cancel_vote,Absent_vote,total_vote,cast_vote
0,1,163,"কোরআনিয়া দারুল উলুম মাদ্রাসাগ্রাম:পেকুয়রচর, ডা...",1740,34,1368,3142,1774
1,1,145,ফাঁসিয়াখালী সরকারী প্রাথমিক বিদ্যালয়গ্রাম: সবজ...,1703,19,677,2399,1722
2,1,164,করিয়ারদিয়া সরকারী প্রাথমিক বিদ্যালয়গ্রামঃ করিয়...,919,19,494,1432,938
3,1,148,"টৈটং হাই স্কুলগ্রাম:+ডাক+ইউনিয়ন: টৈটং, উপজেলা:...",2032,46,823,2901,2078
4,1,32,ঢেমুশিয়া জিন্নত আলী চৌং উচ্চ বিদ্যালয়জমিদার পা...,2078,38,1156,3272,2116
...,...,...,...,...,...,...,...,...
42379,297,146,বড়ধলিয়া জগদীশপুর প্রগতি সরকারী প্রাথমিক বিদ্যা...,2049,51,1570,3670,2100
42380,297,147,"বানেশ্বর সরকারী প্রাথমিক বিদ্যালয়, সাং- বানেশ্...",948,4,891,1843,952
42381,297,148,বানেশ্বর উচ্চ বিদ্যালয় সাং- বানেশ্বরগ্রামঃ বান...,1109,7,827,1943,1116
42382,297,149,"ধনকুড়া সরকারী প্রাথমিক বিদ্যালয়, সাং- ধনকুড়াগ্...",1822,57,1422,3301,1879
42383,297,150,"পাটুলী সরকারী প্রাথমিক বিদ্যালয়, সাং- পাটুলীগ্...",868,16,614,1498,884

File created:

### Extract Candidate-Level Data and Save as Separate File

This section creates a **clean candidate-level dataset** from the combined election data.

In [54]:
file_to_read = os.path.join(processed_folder_path, "all_combined.csv")
combined_df = pd.read_csv(file_to_read, encoding="utf-8-sig")
selected_candidate_data_df = combined_df[[ "seat_id","center_no","candidate_name","symbol","candidate_vote"]].drop_duplicates()
# Reset index
selected_candidate_data_df = selected_candidate_data_df.reset_index(drop=True)

selected_candidate_data_df["seat_id"] = selected_candidate_data_df["seat_id"].astype(int)
selected_candidate_data_df["center_no"] = selected_candidate_data_df["center_no"].astype(int)

selected_candidate_data_df["candidate_vote"] = selected_candidate_data_df["candidate_vote"].astype(int)



display(selected_candidate_data_df)
output_file = os.path.join(processed_folder_path, "candidates_data.csv")
# Save to new CSV
selected_candidate_data_df.to_csv(output_file, index=False, encoding="utf-8-sig")
print("File created:")

,seat_id,center_no,candidate_name,symbol,candidate_vote
0,1,163,আব্দুল্লাহ আল ফারুখ,দাঁড়িপাল্লা,303
1,1,163,মোঃ ছরওয়ার আলম কুতুবী,হাতপাখা,23
2,1,163,সালাহউদ্দিন আহমদ,ধানের শীষ,1414
3,1,145,আব্দুল্লাহ আল ফারুখ,দাঁড়িপাল্লা,670
4,1,145,মোঃ ছরওয়ার আলম কুতুবী,হাতপাখা,10
...,...,...,...,...,...
289903,297,150,মোঃ মিজানুর রহমান চৌধুরী,ঘোড়া,0
289904,297,150,মোঃ মুজিবুর রহমান,মই,0
289905,297,150,মোঃ রাশেদুল ইসলাম খোকন,ছড়ি,0
289906,297,150,শাহ মোঃ আল আমিন,হারিকেন,1
289907,297,150,সালেহ আহমদ সাজন,ফুটবল,0

File created:

# Some COnsistency check

In [55]:
file_to_read = os.path.join(processed_folder_path, "seats.csv")
seat_df = pd.read_csv(file_to_read, encoding="utf-8-sig")
seat_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   zilla_name  297 non-null    object
 1   seat_id     297 non-null    int64
 2   seat_name   297 non-null    object
dtypes: int64(1), object(2)
memory usage: 7.1+ KB

### Get Unique District (Zilla) List

This section extracts all unique district names from the dataset.

---

In [57]:
df_unique=df["zilla_name"].unique().tolist()
print(df_unique)
print(len(df_unique))

['কক্সবাজার', 'কিশোরগঞ্জ', 'কুমিল্লা', 'কুষ্টিয়া', 'কুড়িগ্রাম', 'খাগড়াছড়ি', 'খুলনা', 'গাইবান্ধা', 'গাজীপুর', 'গোপালগঞ্জ', 'চট্টগ্রাম', 'চাঁদপুর', 'চাঁপাইনবাবগঞ্জ', 'চুয়াডাঙ্গা', 'জামালপুর', 'জয়পুরহাট', 'ঝালকাঠি', 'ঝিনাইদহ', 'টাঙ্গাইল', 'ঠাকুরগাঁও', 'ঢাকা', 'দিনাজপুর', 'নওগাঁ', 'নরসিংদী', 'নাটোর', 'নারায়ণগঞ্জ', 'নীলফামারী', 'নেত্রকোনা', 'নোয়াখালী', 'নড়াইল', 'পঞ্চগড়', 'পটুয়াখালী', 'পাবনা', 'পিরোজপুর', 'ফরিদপুর', 'ফেনী', 'বগুড়া', 'বরগুনা', 'বরিশাল', 'বাগেরহাট', 'বান্দরবান', 'ব্রাহ্মণবাড়িয়া', 'ভোলা', 'মাগুরা', 'মাদারীপুর', 'মানিকগঞ্জ', 'মুন্সীগঞ্জ', 'মেহেরপুর', 'মৌলভীবাজার', 'ময়মনসিংহ', 'যশোর', 'রংপুর', 'রাঙ্গামাটি', 'রাজবাড়ী', 'রাজশাহী', 'লক্ষ্মীপুর', 'লালমনিরহাট', 'শরিয়তপুর', 'শেরপুর', 'সাতক্ষীরা', 'সিরাজগঞ্জ', 'সিলেট', 'সুনামগঞ্জ', 'হবিগঞ্জ']
64

In [58]:
df_unique=df["seat_name"].unique().tolist()
print(df_unique)
print(len(df_unique))

['কক্সবাজার-১', 'কক্সবাজার-২', 'কক্সবাজার-৩', 'কক্সবাজার-৪', 'কিশোরগঞ্জ-১', 'কিশোরগঞ্জ-২', 'কিশোরগঞ্জ-৩', 'কিশোরগঞ্জ-৪', 'কিশোরগঞ্জ-৫', 'কিশোরগঞ্জ-৬', 'কুমিল্লা-১', 'কুমিল্লা-১০', 'কুমিল্লা-১১', 'কুমিল্লা-২', 'কুমিল্লা-৩', 'কুমিল্লা-৪', 'কুমিল্লা-৫', 'কুমিল্লা-৬', 'কুমিল্লা-৭', 'কুমিল্লা-৮', 'কুমিল্লা-৯', 'কুষ্টিয়া-১', 'কুষ্টিয়া-২', 'কুষ্টিয়া-৩', 'কুষ্টিয়া-৪', 'কুড়িগ্রাম-১', 'কুড়িগ্রাম-২', 'কুড়িগ্রাম-৩', 'কুড়িগ্রাম-৪', 'খাগড়াছড়ি', 'খুলনা-১', 'খুলনা-২', 'খুলনা-৩', 'খুলনা-৪', 'খুলনা-৫', 'খুলনা-৬', 'গাইবান্ধা-১', 'গাইবান্ধা-২', 'গাইবান্ধা-৩', 'গাইবান্ধা-৪', 'গাইবান্ধা-৫', 'গাজীপুর-১', 'গাজীপুর-২', 'গাজীপুর-৩', 'গাজীপুর-৪', 'গাজীপুর-৫', 'গোপালগঞ্জ-১', 'গোপালগঞ্জ-২', 'গোপালগঞ্জ-৩', 'চট্রগ্রাম-১', 'চট্রগ্রাম-১০', 'চট্রগ্রাম-১১', 'চট্রগ্রাম-১২', 'চট্রগ্রাম-১৩', 'চট্রগ্রাম-১৪', 'চট্রগ্রাম-১৫', 'চট্রগ্রাম-১৬', 'চট্রগ্রাম-৩', 'চট্রগ্রাম-৫', 'চট্রগ্রাম-৬', 'চট্রগ্রাম-৭', 'চট্রগ্রাম-৮', 'চট্রগ্রাম-৯', 'চাঁদপুর-১', 'চাঁদপুর-২', 'চাঁদপুর-৩', 'চাঁদপুর-৪', 'চাঁদপুর-৫', 'চাঁপাইনবাবগঞ্জ-১', 'চাঁপাইনবাবগঞ্জ-২', 'চাঁপাইনবাবগঞ্জ-৩', 'চুয়াডাঙ্গা-১', 'চুয়াডাঙ্গা-২', 'জামালপুর-১', 'জামালপুর-২', 'জামালপুর-৩', 'জামালপুর-৪', 'জামালপুর-৫', 'জয়পুরহাট-১', 'জয়পুরহাট-২', 'ঝালোকাঠি-১', 'ঝালোকাঠি-২', 'ঝিনাইদহ-১', 'ঝিনাইদহ-২', 'ঝিনাইদহ-৩', 'ঝিনাইদহ-৪', 'টাংগাইল-১', 'টাংগাইল-২', 'টাংগাইল-৩', 'টাংগাইল-৪', 'টাংগাইল-৫', 'টাংগাইল-৬', 'টাংগাইল-৭', 'টাংগাইল-৮', 'ঠাকুরগাঁও-১', 'ঠাকুরগাঁও-২', 'ঠাকুরগাঁও-৩', 'ঢাকা-১', 'ঢাকা-১০', 'ঢাকা-১১', 'ঢাকা-১২', 'ঢাকা-১৩', 'ঢাকা-১৪', 'ঢাকা-১৫', 'ঢাকা-১৬', 'ঢাকা-১৭', 'ঢাকা-১৮', 'ঢাকা-১৯', 'ঢাকা-২', 'ঢাকা-২০', 'ঢাকা-৩', 'ঢাকা-৪', 'ঢাকা-৫', 'ঢাকা-৬', 'ঢাকা-৭', 'ঢাকা-৮', 'ঢাকা-৯', 'দিনাজপুর-১', 'দিনাজপুর-২', 'দিনাজপুর-৩', 'দিনাজপুর-৪', 'দিনাজপুর-৫', 'দিনাজপুর-৬', 'নওগাঁ-১', 'নওগাঁ-২', 'নওগাঁ-৩', 'নওগাঁ-৪', 'নওগাঁ-৫', 'নওগাঁ-৬', 'নরসিংদী-১', 'নরসিংদী-২', 'নরসিংদী-৩', 'নরসিংদী-৪', 'নরসিংদী-৫', 'নাটোর-১', 'নাটোর-২', 'নাটোর-৩', 'নাটোর-৪', 'নারায়ণগঞ্জ-১', 'নারায়ণগঞ্জ-২', 'নারায়ণগঞ্জ-৩', 'নারায়ণগঞ্জ-৪', 'নারায়ণগঞ্জ-৫', 'নীলফামারী-১', 'নীলফামারী-২', 'নীলফামারী-৩', 'নীলফামারী-৪', 'নেত্রকোণা-১', 'নেত্রকোণা-২', 'নেত্রকোণা-৩', 'নেত্রকোণা-৪', 'নেত্রকোণা-৫', 'নোয়াখালী-১', 'নোয়াখালী-২', 'নোয়াখালী-৩', 'নোয়াখালী-৪', 'নোয়াখালী-৫', 'নোয়াখালী-৬', 'নড়াইল-১', 'নড়াইল-২', 'পঞ্চগড়-১', 'পঞ্চগড়-২', 'পটুয়াখালী-১', 'পটুয়াখালী-২', 'পটুয়াখালী-৩', 'পটুয়াখালী-৪', 'পাবনা-১', 'পাবনা-২', 'পাবনা-৩', 'পাবনা-৪', 'পাবনা-৫', 'পিরোজপুর-১', 'পিরোজপুর-২', 'পিরোজপুর-৩', 'ফরিদপুর-১', 'ফরিদপুর-২', 'ফরিদপুর-৩', 'ফরিদপুর-৪', 'ফেনী-১', 'ফেনী-২', 'ফেনী-৩', 'বগুড়া-১', 'বগুড়া-২', 'বগুড়া-৩', 'বগুড়া-৪', 'বগুড়া-৫', 'বগুড়া-৬', 'বগুড়া-৭', 'বরগুনা-১', 'বরগুনা-২', 'বরিশাল-১', 'বরিশাল-২', 'বরিশাল-৩', 'বরিশাল-৪', 'বরিশাল-৫', 'বরিশাল-৬', 'বাগেরহাট-১', 'বাগেরহাট-২', 'বাগেরহাট-৩', 'বাগেরহাট-৪', 'বান্দারবান', 'ব্রাক্ষণবাড়িয়া-১', 'ব্রাক্ষণবাড়িয়া-২', 'ব্রাক্ষণবাড়িয়া-৩', 'ব্রাক্ষণবাড়িয়া-৪', 'ব্রাক্ষণবাড়িয়া-৫', 'ব্রাক্ষণবাড়িয়া-৬', 'ভোলা-১', 'ভোলা-২', 'ভোলা-৩', 'ভোলা-৪', 'মাগুড়া-১', 'মাগুড়া-২', 'মাদারিপুর-১', 'মাদারিপুর-২', 'মাদারীপুর-৩', 'মানিকগঞ্জ-১', 'মানিকগঞ্জ-২', 'মানিকগঞ্জ-৩', 'মুন্সিগঞ্জ-১', 'মুন্সিগঞ্জ-২', 'মুন্সিগঞ্জ-৩', 'মেহেরপুর-১', 'মেহেরপুর-২', 'মৌলভীবাজার-১', 'মৌলভীবাজার-২', 'মৌলভীবাজার-৩', 'মৌলভীবাজার-৪', 'ময়মনসিংহ-১', 'ময়মনসিংহ-১০', 'ময়মনসিংহ-১১', 'ময়মনসিংহ-২', 'ময়মনসিংহ-৩', 'ময়মনসিংহ-৪', 'ময়মনসিংহ-৫', 'ময়মনসিংহ-৬', 'ময়মনসিংহ-৭', 'ময়মনসিংহ-৮', 'ময়মনসিংহ-৯', 'যশোর-১', 'যশোর-২', 'যশোর-৩', 'যশোর-৪', 'যশোর-৫', 'যশোর-৬', 'রংপুর-১', 'রংপুর-২', 'রংপুর-৩', 'রংপুর-৪', 'রংপুর-৫', 'রংপুর-৬', 'রাঙ্গামাটি', 'রাজবাড়ী-১', 'রাজবাড়ী-২', 'রাজশাহী-১', 'রাজশাহী-২', 'রাজশাহী-৩', 'রাজশাহী-৪', 'রাজশাহী-৫', 'রাজশাহী-৬', 'লক্ষীপুর-১', 'লক্ষীপুর-২', 'লক্ষীপুর-৩', 'লক্ষীপুর-৪', 'লালমনিরহাট-১', 'লালমনিরহাট-২', 'লালমনিরহাট-৩', 'শরীয়তপুর-১', 'শরীয়তপুর-২', 'শরীয়তপুর-৩', 'শেরপুর-১', 'শেরপুর-২', 'সাতক্ষীরা-১', 'সাতক্ষীরা-২', 'সাতক্ষীরা-৩', 'সাতক্ষীরা-৪', 'সিরাজগঞ্জ-১', 'সিরাজগঞ্জ-২', 'সিরাজগঞ্জ-৩', 'সিরাজগঞ্জ-৪', 'সিরাজগঞ্জ-৫', 'সিরাজগঞ্জ-৬', 'সিলেট-১', 'সিলেট-২', 'সিলেট-৩', 'সিলেট-৪', 'সিলেট-৫', 'সিলেট-৬', 'সুনামগঞ্জ-১', 'সুনামগঞ্জ-২', 'সুনামগঞ্জ-৩', 'সুনামগঞ্জ-৪', 'সুনামগঞ্জ-৫', 'হবিগঞ্জ-১', 'হবিগঞ্জ-২', 'হবিগঞ্জ-৩', 'হবিগঞ্জ-৪']
297

In [59]:
file_to_read = os.path.join(processed_folder_path, "pooling_centres.csv")
pooling_cnteres_df = pd.read_csv(file_to_read, encoding="utf-8-sig")
pooling_cnteres_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42384 entries, 0 to 42383
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   seat_id      42384 non-null  int64
 1   center_no    42384 non-null  int64
 2   center_name  42384 non-null  object
 3   legal_vote   42384 non-null  int64
 4   cancel_vote  42384 non-null  int64
 5   Absent_vote  42384 non-null  int64
 6   total_vote   42384 non-null  int64
dtypes: int64(6), object(1)
memory usage: 2.3+ MB

### Validate Vote Consistency (Data Integrity Check)

This section checks whether the vote totals are logically consistent.

---

In [61]:

df_filtered = pooling_cnteres_df[(pooling_cnteres_df["total_vote"] != pooling_cnteres_df["Absent_vote"] + pooling_cnteres_df["legal_vote"]   + pooling_cnteres_df["cancel_vote"])]
print(df_filtered)

Empty DataFrame
Columns: [seat_id, center_no, center_name, legal_vote, cancel_vote, Absent_vote, total_vote]
Index: []

In [62]:
file_to_read = os.path.join(processed_folder_path, "candidates_data.csv")
candidates_data_df = pd.read_csv(file_to_read, encoding="utf-8-sig")
candidates_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289908 entries, 0 to 289907
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   seat_id         289908 non-null  int64
 1   center_no       289908 non-null  int64
 2   candidate_name  289908 non-null  object
 3   symbol          289908 non-null  object
 4   candidate_vote  289908 non-null  int64
dtypes: int64(3), object(2)
memory usage: 11.1+ MB

In [65]:
grouped_df = candidates_data_df.groupby(["seat_id","center_no"])[["candidate_vote"]].sum()



joined_df = pd.merge(
    pooling_cnteres_df,       # Left table
    grouped_df,               # Right table
    how="left",               # Type of join: left, right, inner, outer
    on=["seat_id", "center_no"]  # Columns to join on
)

display(joined_df)

,seat_id,center_no,center_name,legal_vote,cancel_vote,Absent_vote,total_vote,candidate_vote
0,1,163,"কোরআনিয়া দারুল উলুম মাদ্রাসাগ্রাম:পেকুয়রচর, ডা...",1740,34,1368,3142,1740
1,1,145,ফাঁসিয়াখালী সরকারী প্রাথমিক বিদ্যালয়গ্রাম: সবজ...,1703,19,677,2399,1703
2,1,164,করিয়ারদিয়া সরকারী প্রাথমিক বিদ্যালয়গ্রামঃ করিয়...,919,19,494,1432,919
3,1,148,"টৈটং হাই স্কুলগ্রাম:+ডাক+ইউনিয়ন: টৈটং, উপজেলা:...",2032,46,823,2901,2032
4,1,32,ঢেমুশিয়া জিন্নত আলী চৌং উচ্চ বিদ্যালয়জমিদার পা...,2078,38,1156,3272,2078
...,...,...,...,...,...,...,...,...
42379,297,146,বড়ধলিয়া জগদীশপুর প্রগতি সরকারী প্রাথমিক বিদ্যা...,2049,51,1570,3670,2049
42380,297,147,"বানেশ্বর সরকারী প্রাথমিক বিদ্যালয়, সাং- বানেশ্...",948,4,891,1843,948
42381,297,148,বানেশ্বর উচ্চ বিদ্যালয় সাং- বানেশ্বরগ্রামঃ বান...,1109,7,827,1943,1109
42382,297,149,"ধনকুড়া সরকারী প্রাথমিক বিদ্যালয়, সাং- ধনকুড়াগ্...",1822,57,1422,3301,1822
42383,297,150,"পাটুলী সরকারী প্রাথমিক বিদ্যালয়, সাং- পাটুলীগ্...",868,16,614,1498,868

In [67]:

df_filtered = joined_df[(joined_df["legal_vote"] != joined_df["candidate_vote"])]

print(df_filtered)

Empty DataFrame
Columns: [seat_id, center_no, center_name, legal_vote, cancel_vote, Absent_vote, total_vote, candidate_vote]
Index: []